name: Deploy HTML a Azure Web App - sistema-calificaciones

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login a Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_27E59366E4054ACD8B08781A8C5DD9EE }} 
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9E532BF5BC524BE6AA96D8AA4AB48034 }} 
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2230BAEA06CC4CBD982310A6AA439E38 }}

      - name: Deploy a Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sistema-calificaciones'
          package: ./public_html
